# Usar imagen base de Python
FROM python:3.11-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar el archivo del cliente
COPY client.py .

# Ejecutar el cliente
CMD ["python", "client.py"]